//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutorial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        internal static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini files.
        /// </summary>
        internal static string IniFiles {
            get {
                return ResourceManager.GetString("IniFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenTitle {
            get {
                return ResourceManager.GetString("OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample.
        /// </summary>
        internal static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one;I have {0} ski.;other;I have {0} skis..
        /// </summary>
        internal static string SkisPlural {
            get {
                return ResourceManager.GetString("SkisPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is {0}.
        /// </summary>
        internal static string TodayIs {
            get {
                return ResourceManager.GetString("TodayIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files.
        /// </summary>
        internal static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
    }
}
